spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
    org:
      springframework:
        security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
